@startuml

left to right direction

    actor "Gerente de Compras" as gc
    actor "Supervisor de Estoque" as sde
    actor "Coordenador de Produção" as cp
    actor "Analista de Qualidade" as aq 
    actor "Gerente de Vendas" as gv
    actor Vendedor as vd 


rectangle "Caso de uso" {
   usecase "Organizar Materiais" as UC1  
    usecase "Gerenciar Materiais" as UC2
    usecase "Supervisionar Estoque" as UC3
    usecase "Receber Comissão" as UC4
    usecase "Vender Produtos" as UC5
    usecase "Controlar Vendas" as UC6
    usecase "Comprar Materiais" as UC7
    usecase "Conferir e Verificar Materiais" as UC8
    usecase "Garantir a entrega dos Materiais" as UC9
    usecase "Planejar a utilização dos Materiais" as UC10
    usecase "Monitorar o Processo de Produção" as UC11
    usecase "Conduzir Inspeções Regulares" as UC12
    usecase "Coordenar a entrega dos Produtos" as UC13
    usecase "Registrar todas as Vendas" as UC14 
    usecase "Formar equipe de Vendas" as UC15
    usecase "Cumprir Cotas" as UC16 
}
    vd -- UC4
    vd -- UC16 
    vd -- UC5 
    gv -- UC6 
    gv -- UC15 
    (UC4) .> (UC5) : <<include>> 
    sde -- UC2 
    gv --|> vd 
    gc -- UC7 
    gc --|> sde 
    sde -- UC8
    cp -- UC10
    aq -- UC11
    aq -- UC12 
    vd -- UC13
    vd -- UC14 
    sde -- UC1 
    cp -- UC9 
    sde -- UC3 

@enduml 