@startuml
left to right direction
actor Cliente as c
package Profissional {
  actor "Supervisor de Alimentos" as sa
  actor Chefe as ch
}
package Universidade {
  usecase "Reitor" as UC1
  usecase "Professor" as UC2
  usecase "Aluno" as UC3
  usecase "Suporte" as UC4
  (UC1) .> (UC2) : include
  (UC3) .> (UC2) : <<extends>>
}
sa -- UC4
c -- UC1
c -- UC2
c -- UC3
sa <|-- ch
@enduml
